create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid(),
  visitor_name text not null check (char_length(visitor_name) between 1 and 80),
  status text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  owner_id uuid not null default auth.uid(),
  sender text not null default 'visitor' check (sender in ('visitor', 'team')),
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists messages_conversation_created_idx
  on public.messages (conversation_id, created_at);

alter table public.conversations enable row level security;
alter table public.messages enable row level security;
revoke all on table public.conversations from anon, authenticated;
revoke all on table public.messages from anon, authenticated;
grant select, insert on table public.conversations to authenticated;
grant select, insert on table public.messages to authenticated;
grant usage, select on sequence public.messages_id_seq to authenticated;

create policy "Visitors create their conversation" on public.conversations
for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy "Visitors read their conversation" on public.conversations
for select to authenticated using ((select auth.uid()) = owner_id);
create policy "Visitors send messages" on public.messages
for insert to authenticated with check (
  (select auth.uid()) = owner_id and sender = 'visitor' and exists (
    select 1 from public.conversations c
    where c.id = conversation_id and c.owner_id = (select auth.uid())
  )
);
create policy "Visitors read messages in their conversation" on public.messages
for select to authenticated using (exists (
  select 1 from public.conversations c
  where c.id = conversation_id and c.owner_id = (select auth.uid())
));
